version: '3.8'

services:
  api-db:
    image: sagebionetworks/challenge-registry-api-db:latest
    container_name: challenge-registry-api-db
    restart: always
    env_file:
      - ./apps/api-db/.env
      - .env
    networks:
      - challenge-registry
    ports:
      - "27017:27017"
    volumes:
      - api-db:/data/db

  api:
    image: sagebionetworks/challenge-registry-api:latest
    container_name: challenge-registry-api
    restart: always
    env_file:
      - apps/api/.env
      - .env
    environment:
      - DB_DOMAIN=api-db
    networks:
      - challenge-registry
    ports:
      - "8080:8080"
    depends_on:
      - api-db

  web-app:
    image: sagebionetworks/challenge-registry-web-app:latest
    container_name: challenge-registry-api-web-app
    restart: always
    environment:
      - ENVIRONMENT=prod
      - API_URL=http://localhost/api/v1
      - APP_VERSION=1.0.0
      - SERVICE_HOST=api
      - SERVICE_PORT=8080
    networks:
      - challenge-registry
    ports:
      - "80:80"
    depends_on:
      - api

networks:
  challenge-registry:

volumes:
  api-db:
    name: challenge-registry-api-db