version: "3.8"

services:
  challenge-user-service:
    image: sagebionetworks/challenge-user-service:latest
    container_name: challenge-user-service
    restart: always
    env_file:
      - .env
    networks:
      - challenge
    ports:
      - "8083:8083"
    command: start-dev

networks:
  challenge:
    name: challenge