version: "3.8"

services:
  challenge-elasticsearch:
    image: sagebionetworks/challenge-elasticsearch:latest
    container_name: challenge-elasticsearch
    restart: always
    env_file:
      - .env
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - challenge-elasticsearch:/usr/share/elasticsearch/data:z
    network_mode: "host"
    ports:
      - "9200:9200"
      - "9300:9300"

volumes:
  challenge-elasticsearch:
    name: challenge-elasticsearch

# networks:
#   challenge:
#     name: challenge