version: "3.8"

services:
  keycloak:
    image: sagebionetworks/keycloak:latest
    container_name: keycloak
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/h2:/opt/keycloak/data/h2
    ports:
      - 8081:8080
    command: start-dev
