version: "3.8"

services:
  keycloak:
    image: sagebionetworks/challenge-registry-keycloak:latest
    container_name: challenge-registry-keycloak
    restart: always
    env_file:
      - .env
    volumes:
      - ./imports:/tmp/keycloak/imports
    ports:
      - "8081:8080"
    command: [
      "start-dev",
      "-Dkeycloak.profile.feature.upload_scripts=enabled",
      "-Dkeycloak.migration.file=/tmp/keycloak/imports/realm-test.json"
    ]