version: "3.8"

services:
  challenge-mongo:
    image: sagebionetworks/challenge-mongo:latest
    container_name: challenge-mongo
    restart: always
    env_file:
      - .env
    volumes:
      - challenge-mongo:/data/db
    ports:
      - "27017:27017"

volumes:
  challenge-mongo:
    name: challenge-mongo