version: "3.8"

services:
  challenge-mongodb:
    image: sagebionetworks/challenge-mongodb:latest
    container_name: challenge-mongodb
    restart: always
    env_file:
      - .env
    # networks:
    #   - challenge
    network_mode: "host"
    volumes:
      - challenge-mongodb:/data/db
    ports:
      - "27017:27017"

volumes:
  challenge-mongodb:
    name: challenge-mongodb

networks:
  challenge:
    name: challenge