spring:
  application:
    name: challenge-service-registry

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: ${default.zone}
    fetch-registry: false
    register-with-eureka: false