
spring:
  application:
    name: challenge-auth-service

server:
  port: 8091

eureka:
  client:
    service-url:
      defaultZone: ${service.registry.url}
  instance:
    preferIpAddress: true

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info

info:
  application:
    name: ${spring.application.name}

# app:
  # config:
  #   keycloak:
  #     server-url: ${keycloak.url}
  #     realm: test
  #     clientId: challenge-api-client
  #     client-secret: mg2DrRcxHx19PIITibdOnbNEbJUKjGKb
  # keycloak:
  #   login:
  #     url: http://challenge-keycloak:8080/realms/test/protocol/openid-connect/token
  #   client-id: challenge-core-client
  #   client-secret: O0cNRMWg3LHsdHW8BNPlY96qKooDPhPX
  #   grant-type: password
