version: "3.8"

services:
  challenge-registry-api-db:
    image: sagebionetworks/mongo:4.4.8
    container_name: challenge-registry-api-db
    restart: always
    env_file:
      - .env
    volumes:
      - api-db:/data/db
    ports:
      - "27017:27017"

volumes:
  api-db:
    name: challenge-registry-api-db