name: Build Dev Container Image
on:
  push:
    branches:
      - 'main'
    paths:
      - 'tools/devcontainers/challenge-devcontainer/**/*'
  pull_request:
    paths:
      - 'tools/devcontainers/challenge-devcontainer/**/*'

env:
  IMAGE_REPOSITORY: sagebionetworks/challenge-devcontainer

jobs:
  devcontainer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint Dockerfile
        uses: docker://hadolint/hadolint:latest
        with:
          entrypoint: hadolint
          args: tools/devcontainers/challenge-devcontainer/.devcontainer/Dockerfile

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-single-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-single-buildx

      - name: Set buildx as the default builder
        run: docker buildx install

      - name: Build the image
        run: |
          set -e

          FOLDER_WITH_DOT_DEVCONTAINER="tools/devcontainers/challenge-devcontainer"
          IMAGE_NAME="${{ env.docker_repository }}:${GITHUB_SHA::8}"

          # [Optional] Enable buildkit, set output to plain text for logging
          export DOCKER_BUILDKIT=1
          export BUILDKIT_PROGRESS=plain

          # Build the image
          npm install -g "@vscode/dev-container-cli"
          devcontainer build --image-name "${IMAGE_NAME}" "${FOLDER_WITH_DOT_DEVCONTAINER}"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push the image to Docker Hub
        run: |
          set -e

          # TODO: Define the image name once inside the job
          IMAGE_NAME="${{ env.docker_repository }}:${GITHUB_SHA::8}"

          # Push the image to Docker Hub
          docker push "${IMAGE_NAME}"
