name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  PRIMARY_NODE_VERSION: 14
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}
  NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
  NX_CLOUD_ENV_NAME: 'Node 14.x -'
  NX_VERBOSE_LOGGING : true

jobs:
  main:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout [main]
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.PRIMARY_NODE_VERSION }}
      - run: yarn install --frozen-lockfile
      - run: yarn nx affected --target=build --parallel --max-parallel=3
      - run: yarn nx affected --target=test --parallel --max-parallel=2
  pr:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.PRIMARY_NODE_VERSION }}
      - run: yarn install --frozen-lockfile
      - run: yarn nx affected --target=build --parallel --max-parallel=3 --verbose
      - run: yarn nx affected --target=test --parallel --max-parallel=2 --verbose
